name: 'RHDH Plugin GitOps Updater'
description: 'Monitors and updates dynamic plugins for Red Hat Developer Hub in GitOps repositories'
branding:
  icon: 'refresh-cw'
  color: 'red'

inputs:
  config-path:
    description: 'Path to the dynamic plugins config YAML file (e.g., charts/rhdh/values.yaml)'
    required: true
  config-location:
    description: 'Location of the dynamic plugins config inside the YAML file (e.g., global.dynamic.plugins)'
    required: false
    default: 'global.dynamic.plugins'
  github-token:
    description: 'GitHub token for API access and PR creation'
    required: true
  update-pr-strategy:
    description: 'PR creation strategy: "separate" for individual PRs per plugin, "joint" for one PR with all updates'
    required: false
    default: 'separate'
  pr-creation-limit:
    description: 'Maximum number of PRs to create (0 for unlimited, only applies when update-pr-strategy is "separate")'
    required: false
    default: '0'
  verbose:
    description: 'Enable verbose logging (0 = normal, 1 = verbose/debug)'
    required: false
    default: '0'
  tag-prefixes:
    description: 'Tag prefixes to consider when checking for plugin updates (newline-separated list)'
    required: false
    default: 'next__'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    DYNAMIC_PLUGINS_CONFIG_YAML_FILE_PATH: ${{ inputs.config-path }}
    DYNAMIC_PLUGINS_CONFIG_YAML_LOCATION: ${{ inputs.config-location }}
    GITHUB_TOKEN: ${{ inputs.github-token }}
    UPDATE_PR_STRATEGY: ${{ inputs.update-pr-strategy }}
    PR_CREATION_LIMIT: ${{ inputs.pr-creation-limit }}
    VERBOSE: ${{ inputs.verbose }}
    GH_PACKAGE_TAG_PREFIXES: ${{ inputs.tag-prefixes }}
