name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@eb1897b8dc4b5d5bfe39a428a8f2304605e0983c #v7.0.0
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Run ruff
        run: make ruff

      - name: Run type check
        run: make ty

      - name: Run tests
        run: make test
